#!/bin/bash
echo "Preparing"
appdir=$(dirname "$0")
appdir=$(cd "$appdir" && pwd)
conda install -n base -c conda-forge pyyaml -y
echo "Installing environment..."
ls "$appdir"/env/*.yml > envs.txt
while read i; do
    conda env create -f $i
done < envs.txt
rm envs.txt
