name: Build and publish main Docker image

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and publish envs Docker image"]
    types:
      - completed
  push:
    branches:
      - 'main'
      - 'master'
    tags:
      - v*
  pull_request:
    branches:
      - 'main'
      - 'master'
    tags:
      - v*

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: What
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV 

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.RICARDO_DOCKER_USER }}
          password: ${{ secrets.RICARDO_DOCKER_PASS }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: latest=true
          images: rfcdsantos/flync
          tags: |
            type=raw,value=${{ env.BRANCH }},suffix={{date 'YYYYMMDD'}}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=schedule,pattern={{date 'YYYYMMDD'}}

          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: | 
            BRANCH=${{ env.BRANCH }}
